name = "upradio"
type = "webpack"
account_id = "... your account_id goes here ..."
workers_dev = true
route = ""
zone_id = ""
webpack_config = "./workers-site/webpack.config.js"

kv-namespaces = [
  { binding = "UPRADIO_KV", id = "... your namespace id goes here ..." }
]

[site]
bucket = "dist"
entry-point = "workers-site"